# This file is a template, and might need editing before it works on your project.
#image: golang:latest

#variables:
#  # Please edit to your GitLab project
#  REPO_NAME: gitlab.com/namespace/project

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
#before_script:
#  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
#  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
#  - cd $GOPATH/src/$REPO_NAME
#    - apt upgrade -y --quiet
# nvidia-cuda-dev  nvidia-smi

image: debian:testing

variables:
  CXX: "c++"
  DOCKER_DRIVER: overlay2

before_script:
    - perl -pi -e 's/main/main\ contrib\ non-free/g' /etc/apt/sources.list
    - apt update --quiet
    - DEBIAN_FRONTEND=noninteractive apt install --no-install-recommends --assume-yes --quiet g++ clang libboost-test-dev librange-v3-dev valgrind nvidia-cuda-toolkit 

stages:
    - test
#    - build

gcc:
    stage: test
    script:
      - ln --symbolic --force . ../multi
      - export CXX="g++     -x c++  -Wall -Wextra -Wpedantic -Ofast "
      - $CXX --version
      - cd tests
#      - sh ./array_ptr.cpp
#      - sh ./array_ref.cpp
#      - sh ./sort.cpp
#      - sh ./comparisons.cpp
#      - sh ./constructors.cpp
#      - sh ./initializer_list.cpp
#      - sh ./layout.cpp
#      - sh ./fill.cpp
#      - sh ./rotated.cpp
#      - sh ./allocator.cpp
#      - sh ./reextent.cpp
       - for a in ./*.cpp; do echo $a; sh $a || break; echo "\n"; done;

clang:
    stage: test
    script:
      - ln --symbolic --force . ../multi
      - export CXX="clang++ -x c++ -Wall -Wextra -Wpedantic -Wmove -Ofast "
      - $CXX --version
      - cd tests
      - for a in ./*.cpp; do echo $a; sh $a || break; echo "\n"; done;

